# Generated by Django 3.2.5 on 2021-07-26 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(default='asd-asd', editable=False),
            preserve_default=False,
        ),
    ]
